import type { GetServerSideProps, InferGetServerSidePropsType, NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Breadcrumbs from "../../components/Breadcrumbs";
import ProductDetail from "../../components/ProductDetail";

const ItemDetail: NextPage = ({ data }: InferGetServerSidePropsType<typeof getServerSideProps>) => {
  return (
    <>
      <Head>
        <title>{data.item.title} | Mercado Libre</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.svg" />
      </Head>

      <Breadcrumbs
        breadcrumbs={[
          { link: "", text: "Electronica, Audio y Video" },
          { link: "a", text: "iPod" },
          { link: "b", text: "Reproductores" },
          { link: "c", text: "iPod touch" },
          { link: "d", text: "32 GB" },
        ]}
      />

      <ProductDetail product={data.item} />
    </>
  );
};

export const getServerSideProps: GetServerSideProps = async (context) => {
  const baseUrl = "http://localhost:8080";
  const itemId = context.params?.id;

  const response = await fetch(`${baseUrl}/api/items/${itemId}`);
  const data = await response.json();

  return { props: { data } };
};

export default ItemDetail;
