import type { GetServerSideProps, InferGetServerSidePropsType, NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

const ItemDetail: NextPage = ({ data }: InferGetServerSidePropsType<typeof getServerSideProps>) => {
  return (
    <>
      <Head>
        <title>{data.item.title} | Mercado Libre</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.svg" />
      </Head>

      <Image src={data.item.picture} width={680} height={680}></Image>
    </>
  );
};

export const getServerSideProps: GetServerSideProps = async (context) => {
  const baseUrl = "http://localhost:8080";
  const itemId = context.params?.id;

  const response = await fetch(`${baseUrl}/api/items/${itemId}`);
  const data = await response.json();

  return { props: { data } };
};

export default ItemDetail;
