import type { GetServerSideProps, InferGetServerSidePropsType, NextPage } from "next";
import Head from "next/head";
import { fetchItems } from "../../api/items";
import Product from "../../components/Product";

const Items: NextPage = ({ data, search }: InferGetServerSidePropsType<typeof getServerSideProps>) => {
  return (
    <>
      <Head>
        <title>{ search } | Mercado Libre</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.svg" />
      </Head>

      <ul>{data.items && data.items.map((item: any) => <Product key={item.id} product={item} />)}</ul>
    </>
  );
};

export const getServerSideProps: GetServerSideProps = async ({ query }) => {
  const { search } = query;

  if (!search || typeof search !== "string") {
    return { redirect: { destination: "/", permanent: true } };
  }

  const data = await fetchItems(search);

  return { props: { data, search } };
};

export default Items;
